#!/usr/bin/env python3
"""
author: chien-de li

roadmap
1. use hostname list and command [done]
2. add password support
3. argparse --key
"""
import argparse
import asyncio
import os
from rich.console import Console
from rich.table import Table
from async_ssh.async_ssh import run_on_host, copy_to_host


async def main():
    """
    main function
    """

    parser = argparse.ArgumentParser()
    parser.add_argument('-t',
                        '--hosts',
                        nargs='+',
                        help='<Required> Set hosts list',
                        required=True)
    parser.add_argument('-c',
                        '--command',
                        type=str,
                        help='<Required> Set the command to run',
                        required=True)
    parser.add_argument('-a',
                        '--account',
                        type=str,
                        help='Set the account to run, default $USER',
                        default=os.environ["USER"])
    parser.add_argument('-i',
                        '--key',
                        type=str,
                        help='Set the identity_file, default: ~/.ssh/id_rsa"',
                        default=f"{os.environ['HOME']}/.ssh/id_rsa")
    parser.add_argument('-f', '--files', nargs="+", help="Copy data to hosts")
    parser.add_argument('-T',
                        '--timeout',
                        type=int,
                        help="set timeout to each connection",
                        default=300)

    args = parser.parse_args()
    command = args.command
    account = args.account
    hostnames = args.hosts
    key = args.key
    files = args.files
    timeout = args.timeout

    if files:
        await copy_to_host(hostnames, account, files, key)
    result_dict = await run_on_host(hostnames,
                                    account,
                                    command,
                                    key,
                                    timeout=timeout)

    table = Table(title=f"COMMAND : \"{command}\"")
    table.add_column("Hostname", justify="left", style="cyan", no_wrap=True)
    table.add_column("Result", justify="center", style="green")
    table.add_column("Time", justify="center", style="green")
    for hostname in hostnames:
        if hostname in result_dict.keys():
            table.add_row(hostname, result_dict[hostname]["content"],
                          f'{result_dict[hostname]["time"]}')
        else:
            table.add_row(hostname, "", "")
    console = Console()
    console.print(table)


if __name__ == "__main__":
    asyncio.run(main())
